title: Luca Manolache
email: luca.manolache@berkeley.edu
description: >- 
  My site
baseurl: ""
url: "https://lucamanolache.github.io"
twitter_username: coming soon
github_username:  lucamanolache

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
